#! /bin/sh

# Author: Cameron Taylor
# i3wm setup deployment script for FreeBSD
# Version 1.0 - Fully Dynamic & Portable

# --- DYNAMIC USER DETECTION ---
# Detects the user who initiated the session, even when run as root
if [ "$SUDO_USER" ]; then
    TARGET_USER="$SUDO_USER"
else
    TARGET_USER=$(logname)
fi

USER_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6)
WALLPAPER_URL="https://w.wallhaven.cc/full/xe/wallhaven-xez3dz.png"
WALLPAPER_DEST="/usr/local/share/wallpaper/default-wallpaper.png"

# --- ROOT CHECK ---
if [ "$(id -u)" -ne 0 ]; then
  echo "Error: This script must be run as root (use sudo or su)."
  exit 1
fi

echo "-------------------------------------------------------"
echo "Provisioning FreeBSD for User: $TARGET_USER"
echo "Home Directory: $USER_HOME"
echo "-------------------------------------------------------"

# 1. INSTALL SOFTWARE
echo "Updating pkg and installing software suites..."
pkg update
pkg install -y \
  drm-kmod xorg i3 i3status i3lock i3-gaps dmenu \
  lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings \
  lxappearance picom automount font-awesome \
  arandr firefox chromium pcmanfm lxmenu-data \
  curl calcurse sc-im cmus nitrogen vim mpv conky \
  volumeicon alsa-utils remmina pavucontrol \
  zip zathura eog gammy pwcview webcamd \
  v4l-utils v4l_compat

# 2. SYSTEM CONFIGURATION (rc.conf)
echo "Configuring system services..."
sysrc dbus_enable="YES"
sysrc ntpd_enable="YES"
sysrc moused_enable="YES"
sysrc lightdm_enable="YES"
sysrc webcamd_enable="YES"
sysrc kld_list="i915kms fusefs cuse"

# 3. BOOT & KERNEL TUNABLES
echo "Setting boot loader options..."
sed -i '' '/kern.vty/d' /boot/loader.conf
echo 'kern.vty=vt' >> /boot/loader.conf
sed -i '' '/fusefs_load/d' /boot/loader.conf
echo 'fusefs_load="YES"' >> /boot/loader.conf
sysctl kern.coredump=0
echo "kern.coredump=0" >> /etc/sysctl.conf

# 4. WALLPAPER DOWNLOAD
echo "Downloading wallpaper for LightDM..."
mkdir -p /usr/local/share/wallpaper
fetch -o "$WALLPAPER_DEST" "$WALLPAPER_URL"
chmod 644 "$WALLPAPER_DEST"

# 5. LIGHTDM GREETER CONFIGURATION
echo "Configuring LightDM Greeter..."
GREETER_CONF="/usr/local/etc/lightdm/lightdm-gtk-greeter.conf"
mkdir -p /usr/local/etc/lightdm/
if [ ! -f "$GREETER_CONF" ]; then
    echo "[greeter]\nbackground=$WALLPAPER_DEST" > "$GREETER_CONF"
else
    sed -i '' "s|^#background=.*|background=$WALLPAPER_DEST|" "$GREETER_CONF"
    sed -i '' "s|^background=.*|background=$WALLPAPER_DEST|" "$GREETER_CONF"
fi

# 6. USER PERMISSIONS
echo "Updating group memberships for $TARGET_USER..."
for grp in video wheel webcamd operator; do
  pw groupmod "$grp" -m "$TARGET_USER"
done

# 7. GENERATE .XINITRC
echo "Generating .xinitrc for $TARGET_USER..."
XINITRC="$USER_HOME/.xinitrc"

cat <<EOF > "$XINITRC"
#!/bin/sh
# Generated by FreeBSD setup script

# Start the compositor in the background
picom -f &

# Start i3 within a dbus session
exec ck-launch-session dbus-launch --exit-with-session i3
EOF

chown "$TARGET_USER":"$TARGET_USER" "$XINITRC"
chmod +x "$XINITRC"

echo "-------------------------------------------------------"
echo "Setup Complete!"
echo "User $TARGET_USER has been configured."
echo "Please reboot to start your new i3 desktop."
echo "-------------------------------------------------------"